apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac.yaml
  - sandbox.yaml
  - networkpolicy.yaml
patches:
  - target:
      kind: ServiceAccount
      name: overload
    patch: |-
      - op: replace
        path: /automountServiceAccountToken
        value: true
  - target:
      kind: Deployment
      name: overload
    patch: |-
      - op: replace
        path: /spec/template/spec/automountServiceAccountToken
        value: true
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OVERLOAD_SANDBOX
          value: agent-sandbox
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OVERLOAD_SANDBOX_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OVERLOAD_MODEL_PROXY_URL
          value: http://overload:8083
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          name: model-proxy
          containerPort: 8083
  - target:
      kind: Service
      name: overload
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: model-proxy
          port: 8083
          targetPort: model-proxy
