apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: overload
resources:
  - ../../base
components:
  - ../../components/postgres
images:
  - name: ghcr.io/daltoniam/overload
    newName: overload-app
    newTag: local
patches:
  - target:
      kind: Deployment
      name: overload
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
