apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-from-overload
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: overload
      ports:
        - port: 5432
